version: "3"
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - "./run.py:/run.py"
      - "./app:/app"
    depends_on:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "20k"

  database:
    container_name: database
    image: mongo
    volumes:
      - data-volume:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "10k"

volumes:
  data-volume:
